spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
     # chat:
      #  options:
          #max-tokens: 4800
          #model: gpt-4o
    #Add different model
    #anthropic:
    #  api-key:
    #  chat:
    #    options:
    #      model:
    chat:
      client:
        enabled: false
  application:
    name: aichatbot